import Foundation

enum GameLibrary {
    static let defaultClients: [GameClientDescriptor] = [
        GameClientDescriptor(
            id: "hk4e_cn",
            title: "The Anime Game",
            shortTitle: "GI CN",
            region: "CN",
            serverID: "hk4e_cn",
            server: GameClientServerMetadata(
                channelID: 1,
                subchannelID: 1,
                cpsReference: "CN_CPS",
                launcherUpdateResourceID: "hk4ecn",
                desktopDefaultWineDistributionID: "11.0-dxmt-signed-with-patches",
                blockNetHost: "dispatchcnglobal.yuanshen.com",
                blockNetDurationSeconds: 10,
                removedFiles: [
                    "YuanShen_Data/upload_crash.exe",
                    "YuanShen_Data/Plugins/crashreport.exe",
                    "YuanShen_Data/Plugins/vulkan-1.dll"
                ]
            ),
            gameType: "hk4e",
            releaseType: "cn",
            productName: "YuanShen",
            executable: "YuanShen.exe",
            dataDirectory: "YuanShen_Data",
            latestVersion: "5.3.0",
            currentSupportedVersion: "5.3.0+",
            updatableVersions: ["5.0.0", "5.1.0", "5.2.0"],
            predownloadVersion: "5.4.0",
            predownloadAvailable: true,
            installSize: "120 GiB",
            accentHex: "2F7FD5",
            secondaryHex: "F3C969",
            launchButtonLocation: .right
        ),
        GameClientDescriptor(
            id: "hk4e_global",
            title: "The Anime Game",
            shortTitle: "GI OS",
            region: "Global",
            serverID: "hk4e_global",
            server: GameClientServerMetadata(
                channelID: 1,
                subchannelID: 0,
                cpsReference: "OS_CPS",
                launcherUpdateResourceID: "hk4eos",
                desktopDefaultWineDistributionID: "11.0-dxmt-signed-with-patches",
                blockNetHost: "dispatchosglobal.yuanshen.com",
                blockNetDurationSeconds: 10,
                removedFiles: [
                    "GenshinImpact_Data/upload_crash.exe",
                    "GenshinImpact_Data/Plugins/crashreport.exe",
                    "GenshinImpact_Data/Plugins/vulkan-1.dll"
                ]
            ),
            gameType: "hk4e",
            releaseType: "os",
            productName: "Genshin Impact",
            executable: "GenshinImpact.exe",
            dataDirectory: "GenshinImpact_Data",
            latestVersion: "5.3.0",
            currentSupportedVersion: "5.3.0+",
            updatableVersions: ["5.0.0", "5.1.0", "5.2.0"],
            predownloadVersion: nil,
            predownloadAvailable: false,
            installSize: "118 GiB",
            accentHex: "5D8C6A",
            secondaryHex: "D9B66E",
            launchButtonLocation: .right
        ),
        GameClientDescriptor(
            id: "hkrpg_cn",
            title: "The Space RPG",
            shortTitle: "HSR CN",
            region: "CN",
            serverID: "hkrpg_cn",
            server: GameClientServerMetadata(
                channelID: 1,
                subchannelID: 1,
                cpsReference: "HKRPG_CN_CPS",
                launcherUpdateResourceID: "hkrpgcn",
                desktopDefaultWineDistributionID: "11.0-1-crossover-signed-experimental",
                blockNetHost: "globaldp-prod-cn01.bhsr.com",
                blockNetDurationSeconds: 15,
                removedFiles: [
                    "StarRail_Data/Plugins/x86_64/crashreport.exe",
                    "StarRail_Data/Plugins/x86_64/vulkan-1.dll"
                ]
            ),
            gameType: "hkrpg",
            releaseType: "cn",
            productName: "Star Rail",
            executable: "StarRail.exe",
            dataDirectory: "StarRail_Data",
            latestVersion: "4.3.0",
            currentSupportedVersion: "4.3.0",
            updatableVersions: ["4.0.0", "4.1.0", "4.2.0"],
            predownloadVersion: nil,
            predownloadAvailable: false,
            installSize: "74 GiB",
            accentHex: "7E6AD8",
            secondaryHex: "50C8D8",
            launchButtonLocation: .right
        ),
        GameClientDescriptor(
            id: "hkrpg_global",
            title: "The Space RPG",
            shortTitle: "HSR OS",
            region: "Global",
            serverID: "hkrpg_global",
            server: GameClientServerMetadata(
                channelID: 1,
                subchannelID: 1,
                cpsReference: "HKRPG_OS_CPS",
                launcherUpdateResourceID: "hkrpgos",
                desktopDefaultWineDistributionID: "11.0-1-crossover-signed-experimental",
                blockNetHost: "globaldp-prod-os01.starrails.com",
                blockNetDurationSeconds: 15,
                removedFiles: [
                    "StarRail_Data/Plugins/x86_64/crashreport.exe",
                    "StarRail_Data/Plugins/x86_64/vulkan-1.dll"
                ]
            ),
            gameType: "hkrpg",
            releaseType: "os",
            productName: "Star Rail",
            executable: "StarRail.exe",
            dataDirectory: "StarRail_Data",
            latestVersion: "4.3.0",
            currentSupportedVersion: "4.3.0",
            updatableVersions: ["4.0.0", "4.1.0", "4.2.0"],
            predownloadVersion: nil,
            predownloadAvailable: false,
            installSize: "72 GiB",
            accentHex: "3E5FA8",
            secondaryHex: "C594FF",
            launchButtonLocation: .right
        ),
        GameClientDescriptor(
            id: "nap_cn",
            title: "The Urban Action Game",
            shortTitle: "ZZZ CN",
            region: "CN",
            serverID: "nap_cn",
            server: GameClientServerMetadata(
                channelID: 1,
                subchannelID: 1,
                cpsReference: "NAP_CPS",
                launcherUpdateResourceID: "napcn",
                desktopDefaultWineDistributionID: "11.0-1-crossover-signed-experimental",
                blockNetHost: "globaldp-prod-cn02.juequling.com",
                blockNetDurationSeconds: 20,
                removedFiles: [
                    "ZenlessZoneZero_Data/Plugins/x86_64/vulkan-1.dll"
                ]
            ),
            gameType: "nap",
            releaseType: "cn",
            productName: "NAP",
            executable: "ZenlessZoneZero.exe",
            dataDirectory: "ZenlessZoneZero_Data",
            latestVersion: "3.0.0",
            currentSupportedVersion: "3.0.0",
            updatableVersions: ["2.7.0", "2.8.0", "2.9.0"],
            predownloadVersion: nil,
            predownloadAvailable: false,
            installSize: "86 GiB",
            accentHex: "F0C84B",
            secondaryHex: "2D2F36",
            launchButtonLocation: .left
        ),
        GameClientDescriptor(
            id: "nap_global",
            title: "The Urban Action Game",
            shortTitle: "ZZZ OS",
            region: "Global",
            serverID: "nap_global",
            server: GameClientServerMetadata(
                channelID: 1,
                subchannelID: 0,
                cpsReference: "NAP_CPS",
                launcherUpdateResourceID: "napos",
                desktopDefaultWineDistributionID: "11.0-1-crossover-signed-experimental",
                blockNetHost: "globaldp-prod-os01.zenlesszonezero.com",
                blockNetDurationSeconds: 20,
                removedFiles: [
                    "ZenlessZoneZero_Data/Plugins/x86_64/vulkan-1.dll"
                ]
            ),
            gameType: "nap",
            releaseType: "os",
            productName: "NAP",
            executable: "ZenlessZoneZero.exe",
            dataDirectory: "ZenlessZoneZero_Data",
            latestVersion: "3.0.0",
            currentSupportedVersion: "3.0.0",
            updatableVersions: ["2.7.0", "2.8.0", "2.9.0"],
            predownloadVersion: nil,
            predownloadAvailable: false,
            installSize: "84 GiB",
            accentHex: "E2564A",
            secondaryHex: "F2CB55",
            launchButtonLocation: .left
        ),
        GameClientDescriptor(
            id: "bh3_global",
            title: "The Action RPG",
            shortTitle: "BH3 OS",
            region: "Global",
            serverID: "bh3_global",
            server: GameClientServerMetadata(
                channelID: 0,
                subchannelID: 0,
                cpsReference: "",
                launcherUpdateResourceID: "bh3glb",
                desktopDefaultWineDistributionID: "unstable-bh-wine-1.1",
                blockNetHost: nil,
                blockNetDurationSeconds: nil,
                removedFiles: [
                    "BH3_Data/Plugins/crashreport.exe",
                    "BH3_Data/Plugins/vulkan-1.dll"
                ]
            ),
            gameType: "bh3",
            releaseType: "os",
            productName: "BH3",
            executable: "BH3.exe",
            dataDirectory: "BH3_Data",
            latestVersion: "8.4.0",
            currentSupportedVersion: "7.5.0",
            updatableVersions: ["8.1.0", "8.2.0", "8.3.0"],
            predownloadVersion: nil,
            predownloadAvailable: false,
            installSize: "58 GiB",
            accentHex: "D8508F",
            secondaryHex: "4C78DD",
            launchButtonLocation: .right
        ),
        GameClientDescriptor(
            id: "cbjq_global",
            title: "The Snow Action Game",
            shortTitle: "SCZ OS",
            region: "Global",
            serverID: "CBJQ",
            server: GameClientServerMetadata(
                channelID: 0,
                subchannelID: 0,
                cpsReference: "",
                launcherUpdateResourceID: "cbjq",
                desktopDefaultWineDistributionID: "unstable-bh-gptk-1.0",
                blockNetHost: nil,
                blockNetDurationSeconds: nil,
                removedFiles: [],
                manifestURL: "https://snowbreak-dl.amazingseasuncdn.com/6e5452634164107ee3c3cfd6efcdf55f/PC/updates/manifest.json",
                dlcBaseURL: "https://snowbreak-dl.amazingseasuncdn.com/6e5452634164107ee3c3cfd6efcdf55f/PC/updates/",
                manifestVersion: "2.1.0.83",
                manifestPathOffset: "assets",
                manifestPakCount: 1473,
                manifestPayloadBytes: 19773749106,
                desktopServerChannel: "seasun",
                backgroundURL: "https://cdn1.epicgames.com/spt-assets/e55df6d332b24ee18fb52af2bc530caa/snowbreak-containment-zone-1asa4.jpg"
            ),
            gameType: "cbjq",
            releaseType: "os",
            productName: "CBJQ",
            executable: "Game/Binaries/Win64/Game.exe",
            dataDirectory: "Game",
            latestVersion: "2.1.0",
            currentSupportedVersion: "2.0.0",
            updatableVersions: [],
            predownloadVersion: nil,
            predownloadAvailable: false,
            installSize: "18.4 GiB",
            accentHex: "68B7D8",
            secondaryHex: "E6F2F7",
            launchButtonLocation: .left
        ),
        GameClientDescriptor(
            id: "cbjq_cn",
            title: "The Snow Action Game",
            shortTitle: "SCZ CN",
            region: "CN",
            serverID: "CBJQCN",
            server: GameClientServerMetadata(
                channelID: 0,
                subchannelID: 0,
                cpsReference: "",
                launcherUpdateResourceID: "cbjqcn",
                desktopDefaultWineDistributionID: "v9.2-mingw",
                blockNetHost: nil,
                blockNetDurationSeconds: nil,
                removedFiles: [],
                manifestURL: "https://cbjq.xoyocdn.com/DLC7/PC/updates/manifest.json",
                dlcBaseURL: "https://cbjq.xoyocdn.com/DLC7/PC/updates",
                manifestVersion: "1.8.0.114",
                manifestPathOffset: "assets",
                manifestPakCount: 877,
                manifestPayloadBytes: 17170923455,
                desktopServerChannel: "jinshan",
                backgroundURL: "https://cdn1.epicgames.com/spt-assets/e55df6d332b24ee18fb52af2bc530caa/snowbreak-containment-zone-aeglp.jpg",
                compatibilityNote: "desktop source marks this channel as broken due to AntiCheat"
            ),
            gameType: "cbjq",
            releaseType: "cn",
            productName: "CBJQ",
            executable: "Game/Binaries/Win64/Game.exe",
            dataDirectory: "Game",
            latestVersion: "1.8.0",
            currentSupportedVersion: "2.0.0",
            updatableVersions: [],
            predownloadVersion: nil,
            predownloadAvailable: false,
            installSize: "16.0 GiB",
            accentHex: "7CA7C8",
            secondaryHex: "D8B26A",
            launchButtonLocation: .left
        )
    ]
}
